Algoritmo "protot2 matheus sales"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : EDILENE APARECIDA
// Descrição   : PRIMEIRA ATIVIDADE DE LÓGICA
// Autor(a)    : Nome do(a) aluno(a) matheus sales de moraes

Var

VDV,SM,SF : real

Inicio
 escreval("digite o valor do salario fixo")
   leia(SF)
  }
 }
 escreval("digite o valor de vendas")
  leia(VDV)
  }
 }
 SM <- ((VDV*0.04)+SF)
 }
}
escreval("seu salario foi de ",SM:2:2," R$")

Fimalgoritmo
