Algoritmo "prot matheus sales"







Var

valorreais, valordolares, valoralemao, valorlibras : real

Inicio
 escreval("digite o valor em reais a ser convertido:")
   leia(valorreais)
   valordolares <- (valorreais / 1.8)
  }
 }
   valoralemao <- (valorreais / 2)
  }
 }
   valorlibras <- (valorreais / 3.57)
  }
 }
 escreval("voce tem: ", valordolares:2:2," dolares, ", valoralemao:2:2 , " alemao e ",valorlibras:2:2, " libras")
 

Fimalgoritmo